version: '3.8'
services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.11.3
    depends_on:
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://logstash:5066"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./test/data:/test/data

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.11.3
    ports:
      - "5044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9600"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
